import { PrismaClient, CollegeType, Ownership } from "@prisma/client";
import bcrypt from "bcryptjs";

const prisma = new PrismaClient();

const colleges = [
  {
    name: "Indian Institute of Technology Bombay",
    slug: "iit-bombay",
    location: "Mumbai, Maharashtra",
    city: "Mumbai",
    state: "Maharashtra",
    type: CollegeType.ENGINEERING,
    ownership: Ownership.GOVERNMENT,
    establishedYear: 1958,
    description:
      "IIT Bombay is one of India's premier engineering institutions, known for its cutting-edge research and world-class faculty. Located in Powai, Mumbai, it offers undergraduate, postgraduate, and doctoral programs across engineering, science, design, and management.",
    shortDescription: "India's premier engineering institute in Mumbai",
    website: "https://www.iitb.ac.in",
    rating: 4.8,
    totalRatings: 2340,
    annualFees: 230000,
    hostelFees: 35000,
    naacGrade: "A++",
    nirf: 3,
    approvals: ["AICTE", "UGC", "NAAC"],
    tags: ["IIT", "Premier", "Research", "Engineering"],
    imageUrl: "https://images.unsplash.com/photo-1562774053-701939374585?w=800",
    courses: [
      { name: "B.Tech Computer Science", degree: "B.Tech", duration: 4, totalSeats: 120, fees: 230000 },
      { name: "B.Tech Electrical Engineering", degree: "B.Tech", duration: 4, totalSeats: 80, fees: 230000 },
      { name: "B.Tech Mechanical Engineering", degree: "B.Tech", duration: 4, totalSeats: 80, fees: 230000 },
      { name: "M.Tech Computer Science", degree: "M.Tech", duration: 2, totalSeats: 60, fees: 110000 },
      { name: "MBA", degree: "MBA", duration: 2, totalSeats: 60, fees: 400000 },
    ],
    placements: {
      year: 2024,
      avgPackage: 2400000,
      highestPackage: 25000000,
      medianPackage: 2000000,
      placementRate: 98.5,
      topRecruiters: ["Google", "Microsoft", "Goldman Sachs", "McKinsey", "Amazon", "Apple"],
    },
    facilities: ["Library", "Hostel", "Sports Complex", "Labs", "WiFi", "Gym", "Medical Center", "Cafeteria"],
  },
  {
    name: "Indian Institute of Technology Delhi",
    slug: "iit-delhi",
    location: "New Delhi, Delhi",
    city: "New Delhi",
    state: "Delhi",
    type: CollegeType.ENGINEERING,
    ownership: Ownership.GOVERNMENT,
    establishedYear: 1961,
    description:
      "IIT Delhi is one of the most prestigious engineering institutions in India. Located in Hauz Khas, New Delhi, it has produced some of India's finest engineers, scientists, and entrepreneurs. The institute offers world-class research facilities and excellent industry connections.",
    shortDescription: "Premier engineering institution in India's capital",
    website: "https://www.iitd.ac.in",
    rating: 4.7,
    totalRatings: 2100,
    annualFees: 220000,
    hostelFees: 32000,
    naacGrade: "A++",
    nirf: 2,
    approvals: ["AICTE", "UGC", "NAAC"],
    tags: ["IIT", "Premier", "Research", "Engineering"],
    imageUrl: "https://images.unsplash.com/photo-1580582932707-520aed937b7b?w=800",
    courses: [
      { name: "B.Tech Computer Science", degree: "B.Tech", duration: 4, totalSeats: 100, fees: 220000 },
      { name: "B.Tech Civil Engineering", degree: "B.Tech", duration: 4, totalSeats: 80, fees: 220000 },
      { name: "B.Tech Chemical Engineering", degree: "B.Tech", duration: 4, totalSeats: 60, fees: 220000 },
      { name: "M.Tech VLSI Design", degree: "M.Tech", duration: 2, totalSeats: 40, fees: 100000 },
    ],
    placements: {
      year: 2024,
      avgPackage: 2200000,
      highestPackage: 22000000,
      medianPackage: 1900000,
      placementRate: 97.8,
      topRecruiters: ["Google", "Microsoft", "JP Morgan", "Deloitte", "Samsung"],
    },
    facilities: ["Library", "Hostel", "Sports Complex", "Labs", "WiFi", "Gym", "Medical Center"],
  },
  {
    name: "BITS Pilani",
    slug: "bits-pilani",
    location: "Pilani, Rajasthan",
    city: "Pilani",
    state: "Rajasthan",
    type: CollegeType.ENGINEERING,
    ownership: Ownership.DEEMED,
    establishedYear: 1964,
    description:
      "Birla Institute of Technology and Science, Pilani, is one of India's leading private technical institutes. Known for its unique dual-degree programs and practice school industry internships, BITS has a reputation for producing highly employable graduates who are well-rounded and industry-ready.",
    shortDescription: "Top-ranked deemed university for engineering and science",
    website: "https://www.bits-pilani.ac.in",
    rating: 4.5,
    totalRatings: 3200,
    annualFees: 520000,
    hostelFees: 85000,
    naacGrade: "A",
    nirf: 25,
    approvals: ["UGC", "NAAC", "AIU"],
    tags: ["BITS", "Deemed", "Private", "Engineering"],
    imageUrl: "https://images.unsplash.com/photo-1541339907198-e08756dedf3f?w=800",
    courses: [
      { name: "B.E. Computer Science", degree: "B.E.", duration: 4, totalSeats: 200, fees: 520000 },
      { name: "B.E. Electronics & Instrumentation", degree: "B.E.", duration: 4, totalSeats: 120, fees: 520000 },
      { name: "M.Sc. Mathematics", degree: "M.Sc.", duration: 5, totalSeats: 60, fees: 520000 },
      { name: "M.B.A.", degree: "MBA", duration: 2, totalSeats: 80, fees: 650000 },
    ],
    placements: {
      year: 2024,
      avgPackage: 1800000,
      highestPackage: 15000000,
      medianPackage: 1600000,
      placementRate: 96.2,
      topRecruiters: ["Qualcomm", "Texas Instruments", "Microsoft", "Oracle", "Cisco"],
    },
    facilities: ["Library", "Hostel", "Sports Complex", "Labs", "WiFi", "Swimming Pool", "Medical Center"],
  },
  {
    name: "Delhi University",
    slug: "delhi-university",
    location: "New Delhi, Delhi",
    city: "New Delhi",
    state: "Delhi",
    type: CollegeType.ARTS,
    ownership: Ownership.GOVERNMENT,
    establishedYear: 1922,
    description:
      "University of Delhi, one of the largest and most prestigious universities in India, offers a wide range of undergraduate, postgraduate, and research programs. Its colleges span across North and South campuses offering diverse academic disciplines.",
    shortDescription: "India's largest central university with diverse programs",
    website: "https://www.du.ac.in",
    rating: 4.2,
    totalRatings: 5600,
    annualFees: 25000,
    hostelFees: 20000,
    naacGrade: "A++",
    nirf: 11,
    approvals: ["UGC", "NAAC", "AIU"],
    tags: ["Central University", "Arts", "Commerce", "Science"],
    imageUrl: "https://images.unsplash.com/photo-1607237138185-eedd9c632b0b?w=800",
    courses: [
      { name: "B.A. English Honours", degree: "B.A.", duration: 3, totalSeats: 500, fees: 25000 },
      { name: "B.Com Honours", degree: "B.Com", duration: 3, totalSeats: 800, fees: 20000 },
      { name: "B.Sc. Computer Science", degree: "B.Sc.", duration: 3, totalSeats: 300, fees: 28000 },
      { name: "M.A. Economics", degree: "M.A.", duration: 2, totalSeats: 200, fees: 18000 },
    ],
    placements: {
      year: 2024,
      avgPackage: 650000,
      highestPackage: 3500000,
      medianPackage: 550000,
      placementRate: 78.5,
      topRecruiters: ["Deloitte", "KPMG", "TCS", "Wipro", "Infosys"],
    },
    facilities: ["Library", "Hostel", "Sports Complex", "Labs", "WiFi", "Medical Center"],
  },
  {
    name: "IIM Ahmedabad",
    slug: "iim-ahmedabad",
    location: "Ahmedabad, Gujarat",
    city: "Ahmedabad",
    state: "Gujarat",
    type: CollegeType.MANAGEMENT,
    ownership: Ownership.GOVERNMENT,
    establishedYear: 1961,
    description:
      "Indian Institute of Management Ahmedabad is consistently ranked as one of Asia's best business schools. Its two-year MBA program is among the most competitive and respected globally, known for rigorous academics and exceptional placement outcomes.",
    shortDescription: "Asia's top business school with outstanding placement record",
    website: "https://www.iima.ac.in",
    rating: 4.9,
    totalRatings: 1890,
    annualFees: 2400000,
    hostelFees: 120000,
    naacGrade: "A++",
    nirf: 1,
    approvals: ["AICTE", "UGC", "AACSB", "EQUIS"],
    tags: ["IIM", "MBA", "Premier", "Management"],
    imageUrl: "https://images.unsplash.com/photo-1497366216548-37526070297c?w=800",
    courses: [
      { name: "MBA (PGP)", degree: "MBA", duration: 2, totalSeats: 400, fees: 2400000 },
      { name: "Executive MBA (PGPX)", degree: "MBA", duration: 1, totalSeats: 80, fees: 2800000 },
      { name: "FPM (PhD equivalent)", degree: "FPM", duration: 5, totalSeats: 30, fees: 0 },
    ],
    placements: {
      year: 2024,
      avgPackage: 3600000,
      highestPackage: 120000000,
      medianPackage: 3200000,
      placementRate: 100,
      topRecruiters: ["McKinsey", "BCG", "Bain", "Goldman Sachs", "Sequoia", "Amazon"],
    },
    facilities: ["Library", "Hostel", "Sports Complex", "Case Study Rooms", "WiFi", "Gym", "Medical Center", "Cafeteria"],
  },
  {
    name: "VIT University",
    slug: "vit-university",
    location: "Vellore, Tamil Nadu",
    city: "Vellore",
    state: "Tamil Nadu",
    type: CollegeType.ENGINEERING,
    ownership: Ownership.DEEMED,
    establishedYear: 1984,
    description:
      "VIT University is one of India's largest and well-known private technical universities with campuses across India. It is known for its strong industry-academia partnerships, modern infrastructure, and consistent placement record in top technology companies.",
    shortDescription: "One of India's largest private technical universities",
    website: "https://www.vit.ac.in",
    rating: 4.0,
    totalRatings: 8900,
    annualFees: 198000,
    hostelFees: 75000,
    naacGrade: "A++",
    nirf: 11,
    approvals: ["AICTE", "UGC", "NAAC"],
    tags: ["Deemed", "Private", "Engineering", "Large Campus"],
    imageUrl: "https://images.unsplash.com/photo-1523050854058-8df90110c9f1?w=800",
    courses: [
      { name: "B.Tech Computer Science", degree: "B.Tech", duration: 4, totalSeats: 1200, fees: 198000 },
      { name: "B.Tech Electronics", degree: "B.Tech", duration: 4, totalSeats: 600, fees: 198000 },
      { name: "B.Tech Mechanical", degree: "B.Tech", duration: 4, totalSeats: 600, fees: 195000 },
      { name: "M.Tech Software Engineering", degree: "M.Tech", duration: 2, totalSeats: 200, fees: 185000 },
    ],
    placements: {
      year: 2024,
      avgPackage: 850000,
      highestPackage: 8000000,
      medianPackage: 720000,
      placementRate: 91.3,
      topRecruiters: ["TCS", "Infosys", "Wipro", "Cognizant", "Capgemini", "Accenture"],
    },
    facilities: ["Library", "Hostel", "Sports Complex", "Labs", "WiFi", "Swimming Pool", "Gym", "Medical Center", "Mall"],
  },
  {
    name: "Manipal Institute of Technology",
    slug: "manipal-institute-of-technology",
    location: "Manipal, Karnataka",
    city: "Manipal",
    state: "Karnataka",
    type: CollegeType.ENGINEERING,
    ownership: Ownership.PRIVATE,
    establishedYear: 1957,
    description:
      "Manipal Institute of Technology is part of the Manipal Academy of Higher Education, one of India's premier private universities. MIT Manipal offers a vibrant campus life, strong alumni network, and excellent industry connections.",
    shortDescription: "Premier private engineering college in coastal Karnataka",
    website: "https://manipal.edu/mit",
    rating: 4.1,
    totalRatings: 4500,
    annualFees: 340000,
    hostelFees: 95000,
    naacGrade: "A+",
    nirf: 54,
    approvals: ["AICTE", "UGC", "NAAC"],
    tags: ["Private", "Engineering", "Manipal", "Coastal"],
    imageUrl: "https://images.unsplash.com/photo-1498243691581-b145c3f54a5a?w=800",
    courses: [
      { name: "B.Tech Computer Science", degree: "B.Tech", duration: 4, totalSeats: 480, fees: 340000 },
      { name: "B.Tech Information Technology", degree: "B.Tech", duration: 4, totalSeats: 240, fees: 340000 },
      { name: "B.Tech Biomedical Engineering", degree: "B.Tech", duration: 4, totalSeats: 60, fees: 340000 },
      { name: "M.Tech Data Science", degree: "M.Tech", duration: 2, totalSeats: 60, fees: 290000 },
    ],
    placements: {
      year: 2024,
      avgPackage: 920000,
      highestPackage: 7500000,
      medianPackage: 780000,
      placementRate: 88.7,
      topRecruiters: ["Amazon", "Infosys", "Wipro", "TCS", "Mindtree", "Mphasis"],
    },
    facilities: ["Library", "Hostel", "Sports Complex", "Labs", "WiFi", "Beach Access", "Medical Center"],
  },
  {
    name: "AIIMS New Delhi",
    slug: "aiims-new-delhi",
    location: "New Delhi, Delhi",
    city: "New Delhi",
    state: "Delhi",
    type: CollegeType.MEDICAL,
    ownership: Ownership.GOVERNMENT,
    establishedYear: 1956,
    description:
      "All India Institute of Medical Sciences (AIIMS) New Delhi is India's foremost medical institution. It is the only medical college in India that consistently ranks among the top medical schools globally. AIIMS provides excellence in medical education, research, and patient care.",
    shortDescription: "India's premier medical institution and research center",
    website: "https://www.aiims.edu",
    rating: 4.9,
    totalRatings: 1200,
    annualFees: 6500,
    hostelFees: 10000,
    naacGrade: "A++",
    nirf: 1,
    approvals: ["MCI", "UGC", "NAAC"],
    tags: ["AIIMS", "Medical", "Government", "Premier"],
    imageUrl: "https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?w=800",
    courses: [
      { name: "MBBS", degree: "MBBS", duration: 5, totalSeats: 107, fees: 6500 },
      { name: "MD Medicine", degree: "MD", duration: 3, totalSeats: 50, fees: 4500 },
      { name: "MS Surgery", degree: "MS", duration: 3, totalSeats: 40, fees: 4500 },
      { name: "BSc Nursing", degree: "B.Sc.", duration: 4, totalSeats: 60, fees: 5000 },
    ],
    placements: {
      year: 2024,
      avgPackage: 1200000,
      highestPackage: 5000000,
      medianPackage: 1000000,
      placementRate: 100,
      topRecruiters: ["Government Hospitals", "PGIMER", "Apollo", "Fortis", "Max Healthcare"],
    },
    facilities: ["Library", "Hostel", "Labs", "Hospital", "WiFi", "Medical Center", "Research Center"],
  },
  {
    name: "National Law School of India University",
    slug: "nlsiu-bangalore",
    location: "Bengaluru, Karnataka",
    city: "Bengaluru",
    state: "Karnataka",
    type: CollegeType.LAW,
    ownership: Ownership.GOVERNMENT,
    establishedYear: 1987,
    description:
      "National Law School of India University (NLSIU) Bangalore is India's foremost law school and a pioneer of legal education reform in the country. Its five-year integrated BA LLB program is considered the gold standard for legal education in India.",
    shortDescription: "India's top law school and pioneer of legal education",
    website: "https://nls.ac.in",
    rating: 4.7,
    totalRatings: 980,
    annualFees: 220000,
    hostelFees: 55000,
    naacGrade: "A",
    nirf: 1,
    approvals: ["BCI", "UGC", "NAAC"],
    tags: ["NLU", "Law", "Government", "Premier"],
    imageUrl: "https://images.unsplash.com/photo-1589829545856-d10d557cf95f?w=800",
    courses: [
      { name: "BA LLB (Hons)", degree: "BA LLB", duration: 5, totalSeats: 80, fees: 220000 },
      { name: "LLM", degree: "LLM", duration: 1, totalSeats: 30, fees: 150000 },
      { name: "PhD Law", degree: "PhD", duration: 3, totalSeats: 20, fees: 80000 },
    ],
    placements: {
      year: 2024,
      avgPackage: 1800000,
      highestPackage: 8000000,
      medianPackage: 1500000,
      placementRate: 95.5,
      topRecruiters: ["AZB Partners", "Cyril Amarchand", "Trilegal", "Khaitan & Co", "Supreme Court"],
    },
    facilities: ["Library", "Hostel", "Moot Court", "Labs", "WiFi", "Medical Center", "Sports Ground"],
  },
  {
    name: "IIT Madras",
    slug: "iit-madras",
    location: "Chennai, Tamil Nadu",
    city: "Chennai",
    state: "Tamil Nadu",
    type: CollegeType.ENGINEERING,
    ownership: Ownership.GOVERNMENT,
    establishedYear: 1959,
    description:
      "IIT Madras, located on a beautiful forested campus in Chennai, is ranked as India's best institution by NIRF consistently. Known for strong research output, deep tech startups, and a vibrant campus culture centered around its famous deer park.",
    shortDescription: "NIRF's #1 ranked institution in India",
    website: "https://www.iitm.ac.in",
    rating: 4.9,
    totalRatings: 2800,
    annualFees: 225000,
    hostelFees: 33000,
    naacGrade: "A++",
    nirf: 1,
    approvals: ["AICTE", "UGC", "NAAC"],
    tags: ["IIT", "Premier", "Research", "NIRF #1"],
    imageUrl: "https://images.unsplash.com/photo-1562774053-701939374585?w=800",
    courses: [
      { name: "B.Tech Computer Science", degree: "B.Tech", duration: 4, totalSeats: 110, fees: 225000 },
      { name: "B.Tech Aerospace Engineering", degree: "B.Tech", duration: 4, totalSeats: 50, fees: 225000 },
      { name: "B.Tech Naval Architecture", degree: "B.Tech", duration: 4, totalSeats: 40, fees: 225000 },
      { name: "M.Tech AI", degree: "M.Tech", duration: 2, totalSeats: 50, fees: 108000 },
    ],
    placements: {
      year: 2024,
      avgPackage: 2600000,
      highestPackage: 28000000,
      medianPackage: 2100000,
      placementRate: 99.0,
      topRecruiters: ["Google", "Microsoft", "Intel", "Qualcomm", "ISRO", "DRDO"],
    },
    facilities: ["Library", "Hostel", "Sports Complex", "Labs", "WiFi", "Deer Park", "Medical Center", "Cafeteria"],
  },
  {
    name: "Symbiosis International University",
    slug: "symbiosis-international-university",
    location: "Pune, Maharashtra",
    city: "Pune",
    state: "Maharashtra",
    type: CollegeType.MANAGEMENT,
    ownership: Ownership.DEEMED,
    establishedYear: 2002,
    description:
      "Symbiosis International University is a multi-institutional, multi-disciplinary deemed university in Pune. It hosts several constituent institutions including SIBM, SCMHRD, and SIOM, and is known for strong management programs and international collaborations.",
    shortDescription: "Multi-disciplinary deemed university known for management programs",
    website: "https://www.siu.edu.in",
    rating: 4.0,
    totalRatings: 3400,
    annualFees: 1200000,
    hostelFees: 110000,
    naacGrade: "A",
    nirf: 36,
    approvals: ["AICTE", "UGC", "NAAC", "AIU"],
    tags: ["Deemed", "Management", "MBA", "Pune"],
    imageUrl: "https://images.unsplash.com/photo-1497366216548-37526070297c?w=800",
    courses: [
      { name: "MBA (SIBM)", degree: "MBA", duration: 2, totalSeats: 240, fees: 1200000 },
      { name: "BBA", degree: "BBA", duration: 3, totalSeats: 320, fees: 350000 },
      { name: "B.Tech Computer Science", degree: "B.Tech", duration: 4, totalSeats: 180, fees: 460000 },
      { name: "BA LLB", degree: "BA LLB", duration: 5, totalSeats: 80, fees: 320000 },
    ],
    placements: {
      year: 2024,
      avgPackage: 1400000,
      highestPackage: 6000000,
      medianPackage: 1200000,
      placementRate: 93.8,
      topRecruiters: ["HDFC Bank", "Deloitte", "EY", "Amazon", "Flipkart", "TCS"],
    },
    facilities: ["Library", "Hostel", "Sports Complex", "Labs", "WiFi", "Gym", "Medical Center"],
  },
  {
    name: "Jadavpur University",
    slug: "jadavpur-university",
    location: "Kolkata, West Bengal",
    city: "Kolkata",
    state: "West Bengal",
    type: CollegeType.ENGINEERING,
    ownership: Ownership.GOVERNMENT,
    establishedYear: 1955,
    description:
      "Jadavpur University is one of India's premier state universities located in Kolkata. Known for its engineering and humanities departments, it has produced numerous scientists, engineers, and Nobel laureates among its alumni.",
    shortDescription: "Premier state university with strong engineering and humanities",
    website: "https://jadavpuruniversity.in",
    rating: 4.3,
    totalRatings: 2900,
    annualFees: 18000,
    hostelFees: 15000,
    naacGrade: "A++",
    nirf: 14,
    approvals: ["AICTE", "UGC", "NAAC"],
    tags: ["State University", "Engineering", "Research", "Kolkata"],
    imageUrl: "https://images.unsplash.com/photo-1580582932707-520aed937b7b?w=800",
    courses: [
      { name: "B.E. Computer Science", degree: "B.E.", duration: 4, totalSeats: 120, fees: 18000 },
      { name: "B.E. Electrical Engineering", degree: "B.E.", duration: 4, totalSeats: 100, fees: 18000 },
      { name: "B.A. English", degree: "B.A.", duration: 3, totalSeats: 200, fees: 8000 },
      { name: "M.E. Software Engineering", degree: "M.E.", duration: 2, totalSeats: 40, fees: 15000 },
    ],
    placements: {
      year: 2024,
      avgPackage: 780000,
      highestPackage: 4500000,
      medianPackage: 660000,
      placementRate: 85.2,
      topRecruiters: ["TCS", "Infosys", "Wipro", "HCL", "Capgemini", "IBM"],
    },
    facilities: ["Library", "Hostel", "Sports Complex", "Labs", "WiFi", "Medical Center"],
  },
];

async function main() {
  console.log("🌱 Starting seed...");

  // Create a demo user
  const hashedPassword = await bcrypt.hash("demo@1234", 10);
  const user = await prisma.user.upsert({
    where: { email: "demo@collegediscovery.in" },
    update: {},
    create: {
      name: "Demo User",
      email: "demo@collegediscovery.in",
      password: hashedPassword,
    },
  });
  console.log(`✅ Created user: ${user.email}`);

  for (const data of colleges) {
    const { courses, placements, facilities, ...collegeData } = data;

    const college = await prisma.college.upsert({
      where: { slug: collegeData.slug },
      update: {},
      create: {
        ...collegeData,
        courses: {
          create: courses.map((c) => ({
            name: c.name,
            degree: c.degree,
            duration: c.duration,
            totalSeats: c.totalSeats,
            fees: c.fees,
          })),
        },
        placements: {
          create: {
            year: placements.year,
            avgPackage: placements.avgPackage,
            highestPackage: placements.highestPackage,
            medianPackage: placements.medianPackage,
            placementRate: placements.placementRate,
            topRecruiters: placements.topRecruiters,
          },
        },
        facilities: {
          create: facilities.map((name) => ({ name, available: true })),
        },
      },
    });

    // Seed a review per college
    await prisma.review.upsert({
      where: { id: `review-${college.id}` },
      update: {},
      create: {
        id: `review-${college.id}`,
        collegeId: college.id,
        userId: user.id,
        rating: parseFloat((Math.random() * 1.5 + 3.5).toFixed(1)),
        title: "Great learning experience overall",
        content:
          "The faculty here is exceptional and the infrastructure is world-class. The campus has a vibrant culture with many clubs and events. Placements are excellent with top companies visiting every year. Overall, a great place to study and grow professionally.",
        pros: "Excellent faculty, great infrastructure, strong alumni network",
        cons: "Highly competitive environment, limited seats, high fees",
        batch: 2022,
        course: courses[0].name,
      },
    });

    console.log(`✅ Seeded: ${college.name}`);
  }

  console.log("🎉 Seed complete!");
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
